# Generated by Django 5.2.16 on 2026-07-20 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SearchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=200, verbose_name='搜索关键词')),
                ('search_type', models.CharField(default='all', max_length=20, verbose_name='搜索类型')),
                ('result_count', models.PositiveIntegerField(default=0, verbose_name='结果数量')),
                ('searched_at', models.DateTimeField(auto_now_add=True, verbose_name='搜索时间')),
            ],
            options={
                'verbose_name': '搜索历史',
                'verbose_name_plural': '搜索历史',
                'db_table': 'study_search_history',
                'ordering': ['-searched_at'],
            },
        ),
        migrations.CreateModel(
            name='StudyBackup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='备份名称')),
                ('data', models.TextField(verbose_name='备份数据')),
                ('file_size', models.PositiveIntegerField(default=0, verbose_name='文件大小(字节)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '数据备份',
                'verbose_name_plural': '数据备份',
                'db_table': 'study_backups',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudyCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='分类名称')),
                ('color', models.CharField(blank=True, default='', max_length=20, verbose_name='颜色标识')),
                ('is_default', models.BooleanField(default=False, verbose_name='默认分类')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '学习分类',
                'verbose_name_plural': '学习分类',
                'db_table': 'study_categories',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='StudyGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(choices=[('daily', '每日'), ('weekly', '每周'), ('monthly', '每月')], max_length=10, unique=True, verbose_name='目标周期')),
                ('target_minutes', models.PositiveIntegerField(verbose_name='目标时长(分钟)')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '学习目标',
                'verbose_name_plural': '学习目标',
                'db_table': 'study_goals',
            },
        ),
        migrations.CreateModel(
            name='StudyNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('content', models.TextField(verbose_name='内容')),
                ('tags', models.CharField(blank=True, default='', max_length=500, verbose_name='标签')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '学习笔记',
                'verbose_name_plural': '学习笔记',
                'db_table': 'study_notes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudyRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, verbose_name='学习日期')),
                ('subject', models.CharField(max_length=200, verbose_name='学习主题')),
                ('duration', models.PositiveIntegerField(default=0, verbose_name='学习时长(分钟)')),
                ('content', models.TextField(blank=True, default='', verbose_name='学习内容')),
                ('category', models.CharField(db_index=True, default='其他', max_length=50, verbose_name='分类')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '学习记录',
                'verbose_name_plural': '学习记录',
                'db_table': 'study_records',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudyTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='任务标题')),
                ('description', models.TextField(blank=True, default='', verbose_name='任务描述')),
                ('priority', models.CharField(choices=[('high', '高'), ('medium', '中'), ('low', '低')], default='medium', max_length=10, verbose_name='优先级')),
                ('due_date', models.DateField(db_index=True, verbose_name='截止日期')),
                ('completed', models.BooleanField(default=False, verbose_name='已完成')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '学习任务',
                'verbose_name_plural': '学习任务',
                'db_table': 'study_tasks',
                'ordering': ['completed', 'due_date'],
            },
        ),
    ]
